config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :cities do
    resources :suggestions, only: [:index, :show, :new, :create] do
      resources :comments, only: [:index, :show, :new, :create]
    end
  end
end

app/models/city.rb
# City Model File
class City < ActiveRecord::Base
  has_many :suggestions, dependent: :destroy

  validates :city_name, :country_name, presence: true
end

app/models/comment.rb
# Comment Model File
class Comment < ActiveRecord::Base
  belongs_to :suggestion

  validates :body, presence: true
end

app/models/suggestion.rb
# Suggestion Model
class Suggestion < ActiveRecord::Base
  CATEGORIES = %w{ 18+ Outdoors Food Entertainment Sightseeing Combination}

  belongs_to :city
  has_many :comments, dependent: :destroy

  validates :ideas, presence: true
  validates :category, inclusion: {in: CATEGORIES, message: "is Invalid"}
end

app/controllers/application_controller.rb
# Not sure what should go here but rubocop wants something
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
# Controller for cities model
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  def index
    @cities = City.all.order('country_name ASC').order('city_name ASC')
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @cities }
    end
  end

  def show
  end

  def new
    @city = City.new
  end

  def create
    @city = City.new(city_params)
    if @city.save
      redirect_to @city, notice: 'City was successfully added'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @city.update(city_params)
      redirect_to @city, notice: 'City was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @city.destroy
    redirect_to cities_url, notice: 'City was successfully destroyed.'
  end

  private

  def set_city
    @city = City.find(params[:id])
  end

  def city_params
    params.require(:city).permit(:city_name, :country_name, :photo_url)
  end
end

app/controllers/comments_controller.rb
# Comments Controller
class CommentsController < ApplicationController
  before_action :set_city
  before_action :set_suggestion

  def index
    @comments = @suggestion.comments
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = @suggestion.comments.build(comment_params)
    if @comment.save
      redirect_to city_suggestion_path(@city, @suggestion), notice:
      'Comment successfully created.'
    else
      render :new
    end
  end

  def show
    @comment = @suggestion.comments.find(params[:id])
  end

  private

  def set_city
    @city = City.find(params[:city_id])
  end

  def set_suggestion
    @suggestion = @city.suggestions.find(params[:suggestion_id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/suggestions_controller.rb
# Suggestions Controller
class SuggestionsController < ApplicationController
  before_action :set_city

  def index
    @suggestions = @city.suggestions.order('category ASC')
  end

  def new
    @suggestion = Suggestion.new
  end

  def create
    @suggestion = Suggestion.new(suggestion_params)
    @suggestion.city = City.find(params[:city_id])
    if @suggestion.save
      redirect_to city_path(@city.id), notice:
      'Suggestion was successfully added'
    else
      render :new
    end
  end

  def show
    @suggestion = @city.suggestions.find(params[:id])
  end

  private

  def set_city
    @city = City.find(params[:city_id])
  end

  def suggestion_params
    params.require(:suggestion).permit(:name, :ideas, :category)
  end
end

app/controllers/welcome_controller.rb
# Welcome Controller
class WelcomeController < ApplicationController
  def index
    @home_page = true
  end
end

app/helpers/application_helper.rb
# Helper
module ApplicationHelper
end

app/helpers/cities_helper.rb
# Helper
module CitiesHelper
end

app/helpers/welcome_helper.rb
# Helper
module WelcomeHelper
end

app/views/cities/_form.html.erb
<%= form_for(@city) do |f|  %>
  <div class="field">
    <%= f.label :city_name %><br>
    <%= f.text_field :city_name %>
  </div>
  <div class="field">
    <%= f.label :country_name %><br>
    <%= f.text_field :country_name%>
  </div><br>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing a city?</h1>

<%= render 'form' %>

<%= button_to 'Delete City', city_path(@city), method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/cities/index.html.erb
<p id="notice"><%= notice %></p>

<div class="navbar">
  <ul class="nav nav-pills pull-left">
    <li><%= link_to 'Back to Homepage', root_path %></li>
  </ul>

</div>
<div class="jumbotron-welcome">
  <div class="container">
    <h1 class="header-index">Fueling</h1>
    <div class="col-lg-12">
      <img class="img-responsive" src="http://3.bp.blogspot.com/-qP4_OfnqB0Q/UeFsfbZCsJI/AAAAAAAAAwo/yHSsXuP2jw4/s1600/header%2Bnanan%2Bpng%25282%2529.png">
    </div>
  </div>
</div>
<div class="body">
  <div class="container">
    <h2> Cities </h2>
    <ul>
      <% @cities.each do |city| %>
      <div>
        <div class="city_country"> <%= city.city_name %>, <%= city.country_name  %> --  <%= link_to 'Explore', city %> </div>
      </div>
      <% end %>
    </ul>
  </div>
</div>

<div class="footer"><p>Don't see a city you'd like to learn more about? Keep checking in or send an email to <a href="mailto:asbren13@gmail.com">asbren13@gmail.com</a> with your city recommendation!</p></div>

app/views/cities/new.html.erb
<h1>Adding a new City</h1>
<%= render 'form' %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>
<div class="navbar">
  <ul class="nav nav-pills pull-left">
    <li><%= link_to 'Back to Homepage', root_path %></li>
  </ul>
  <ul class ="nav nav-pills pull-right">
    <li><%= link_to 'All Cities', cities_path%></li>
    <li><%= link_to 'Add your suggestion!', new_city_suggestion_path(@city, @suggestion)%></li>
  </ul>
</div>


<div class="header-show">
  <div class="col-lg-14">
    <img class="img-responsive" src="<%= @city.photo_url %>">
  </div>
</div>
<h3 class="header-text">Suggestions for <%= @city.city_name %> </h3>


<div class="suggestions">
  <% @city.suggestions.order('category ASC').each do |suggestion| %>
  <div>
    <div class="name"> <%= suggestion.name %> </div>
    <div class="category"><%= suggestion.category %></div>
    <div class="suggestion"><%= suggestion.ideas %>
    </div>
    <%= link_to 'View this suggestion!', city_suggestion_path(@city, suggestion)%>
    <div class="comments"><%= suggestion.comments.count %> Comments for this suggestion</div>
  </div>
  <% end %>
</div>

app/views/comments/_form.html.erb
<div class="container">
  <%= form_for [@city, @suggestion, @comment] do |f| %>
    <div class="form-group">
      <%= f.label :body, "Enter your comment here:" %>
    <div class="form-group">
      <%= f.text_area :body, :cols => "110", :rows => "5" %>
      </div>
    <div class="form-group">
      <%= f.submit "Submit" %>
      </div>
    </div>
  <% end %>
</div>

app/views/comments/index.html.erb
<h1>Comments</h1>

<h2>hello </h2>

<% @comments.each do |comment| %>
  <li><p><%= comment.body %></p></li>
<% end %>

app/views/comments/new.html.erb
<div class="navbar">
  <ul class="nav nav-pills pull-left">
    <li><%= link_to 'Back to Homepage', cities_path %></li>
  </ul>
  <ul class ="nav nav-pills pull-right">
    <li><%= link_to 'Back to Previous Page', city_suggestion_path(@city, @suggestion) %></li>
  </ul>
</div>
<div class="header-show">
  <div class="col-lg-14">
    <img class="img-responsive" src="<%= @city.photo_url %>">
  </div>
</div>
<h1 class="header">Adding a new Comment</h1>
<%= render 'form' %>

app/views/comments/show.html.erb
<h1>Comments</h1>
<h2>hello </h2>
<div><%= @comment.body %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FuelingWanderlust</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= google_webfonts_init({
    google: ['Calligraffitti', 'Raleway']
  }) %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/suggestions/_form.html.erb
<div class="container">
<%= form_for [@city, @suggestion] do |f| %>
  <div class="form-group">
    <%= f.label :name, "Name:" %>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :ideas, "Ideas:" %>
    <%= f.text_area :ideas, :cols => "110", :rows => "5"%>
  </div>
   <div class="form-group">
    <%= f.label :category %><br>
    <%= f.select :category, Suggestion::CATEGORIES, prompt: "Pick one" %>
  <div class="form-group">
    <%= f.submit "Submit" %>
    </div>
<% end %>
</div>

app/views/suggestions/index.html.erb
<p id="notice"><%= notice %></p>
<div class="navbar">
  <ul class="nav nav-pills pull-left">
    <li><%= link_to 'Back to Homepage', cities_path %></li>
  </ul>
  <ul class ="nav nav-pills pull-right">
    <li><%= link_to 'Back to City', city_path(@city) %></li>
    <li><%= link_to 'Add your suggestion!', new_city_suggestion_path(@city, @suggestion)%></li>
  </ul>
</div>

<div class="header"><h1>Suggestions</h1>

  <ul>
    <% @suggestions.each do |suggestion| %>
    <li>
      <%= suggestion.name %>
      <%= suggestion.ideas %> <%= link_to 'View this suggestion!', city_suggestion_path(@city, suggestion)%>
    </li>
    <% end %>
  </ul>
</div>

app/views/suggestions/new.html.erb
<div class="navbar">
  <ul class="nav nav-pills pull-left">
    <li><%= link_to 'Back to Homepage', root_path %></li>
  </ul>
    <ul class ="nav nav-pills pull-right">
      <li><%= link_to 'Back to City', city_path(@city) %></li>
    </ul>
</div>
<div class="header-show">
  <div class="col-lg-14">
    <img class="img-responsive" src="<%= @city.photo_url %>">
  </div>
</div>

<h1 class="header">Adding a new Suggestion</h1>

<br>
<%= render 'form' %>

app/views/suggestions/show.html.erb
<p id="notice"><%= notice %></p>
<div class="navbar">
  <ul class="nav nav-pills pull-left">
    <li><%= link_to 'Back to Homepage', root_path %></li>
  </ul>
  <ul class ="nav nav-pills pull-right">
    <li><%= link_to 'Back to City', city_path(@city) %></li>
    <li><%= link_to 'Add a Comment', new_city_suggestion_comment_path(@city, @suggestion, @comment) %></li>
  </ul>
</div>
<div class="header-show">
  <div class="col-lg-14">
    <img class="img-responsive" src="<%= @city.photo_url %>">
  </div>
</div>
<div class="container">
  <h1>Suggestion from <%= @suggestion.name %>:</h1>
  <br>
  <div class="suggestions-show">
    <div ><%= @suggestion.ideas %></div>
    <br>
    <h3>All Comments :</h3>

    <% @suggestion.comments.each do |comment| %>
    <ul>
      <li>
        <%= comment.body %>
      </li>
    </ul>
    <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
<body class="homepage">
  <div class="header">
    <h1 class="header-welcome">Fueling</h1>
    <div class="col-lg-12">
      <img class="img-responsive" src="http://3.bp.blogspot.com/-qP4_OfnqB0Q/UeFsfbZCsJI/AAAAAAAAAwo/yHSsXuP2jw4/s1600/header%2Bnanan%2Bpng%25282%2529.png">
    </div>
  </div>
  <div class="welcome-page">
    Click below to see a list of cities
    <div class="dropdown menu">
      Pick a location you're interested in exploring!
      <form class="filter_locations", action="", method="get">
       <% @options = City.all.order("country_name ASC").order("city_name ASC").map { |a| [  a.city_name+', ' + a.country_name, a.id] } %>
       <%= select_tag "city", options_for_select(@options), :onchange => "this.form.action = '/cities/' +\
       this.value;", :include_blank => true %>
       <%= submit_tag "Submit" %>
     </form>
   </div>
 </div>
 <div class="above-footer">
  <%= link_to 'See a List of All Cities', cities_path(@city)%>
</div>
<div class="footer"><p>Don't see a city you'd like to learn more about? Keep checking in or send an email to <a href="mailto:asbren13@gmail.com">asbren13@gmail.com</a> with your city recommendation!</p></div>

</body>